### ISSUE TITLE
Own reducer tree in combination with `redux-routes`

### ISSUE THREAD

**Issue by akoenig** [matthewmueller/socrates#10]
First of all: Thanks for this awesome abstraction which removes _a lot_ boilerplate code you have to write over and over again.

Currently I'm working on an own reducer tree in combination with `redux-routes`. I'm struggling with the question how to update the route url when using my own reducer tree. Consider the following code:

``` js
import {render, h} from 'preact-socrates'
import Socrates from 'socrates'
import Logger from 'redux-logger'
import History, {navigate} from 'redux-routes'
import Route from 'enroute';

const store = Socrates([
    Logger(),
    History()
], {
    boot(state, action) {
        return action
    },
        // How to update the url?
    user: {
        update(state, action) {
            return action.name;
        }
    }
});

const Root = ({url}) =>
    Route({
        '/users': params => <div>Users</div>
    })(url);

store('boot', {
    url: document.location.pathname,
    user: 'A user name'
});

store(navigate('/users'));

render(Root, store, document.getElementById('app'));
```

Could you point me in the right direction how to update `url` in my state when using the `redux-routes` middleware?

Thanks in advance :)

**Comment by matthewmueller** [comment]
sorry for the delay here, you'll need to do something like this:

``` js
{
    '@@redux/navigation': function (state, action) { return action }
}
```

this is a bit goofy i know, i'm changing how i do this now.
