### ISSUE TITLE
Root reducers

### ISSUE THREAD

**Issue by sebas5384** [matthewmueller/socrates#4]
Hey! first of all, awesome lib :)

Could the reducers always get the root state, not just an scoped state?

thanks!

**Comment by matthewmueller** [comment]
Thanks for the kind words :-)

If you're talking about using the reducer tree, you should be able to do:

``` js
let store = Socrates({
  boot(state, action) {
     // full state object
     // action = "boot"
  }
})
```

where `boot` is the action, so you could dispatch like this:

``` js
store('boot', state)
```

**Comment by sebas5384** [comment]
Hmm, so in order to get the full state object I have to always make a root reducer.

My doubt is because sometimes I want to update or access the full state from a reducer like `user.settings.change`:

```
app: {
    enabledThemes: ['blue']
},
user: {
    // run with type: "update user"
    update(state, action) {
      return action
    },
    settings: {
      // run with type: "change user.settings"
      change(state, action) {
        // state & action only contain the relevate data
        // you only need to return an action, because socrates
        // updates, doesn't replace.
        // 3. state = { theme: "red" }
        // 4. action = { theme: "blue" }
        return action
      }
    }
  }
```

imagine that I want to restrict  the `theme: 'blue'` only if `action.theme in state.app.enabledThemes`.
So, in every action, even like `change user.settings` action is fired, the reducer haves full state access.

**Comment by matthewmueller** [comment]
ahh i see. 

right now i'm going to keep it as is, since people are having success with redux's combineReducer which does the same thing (of modifying the state scope), but if we run  into issues with this I'm open to new ideas / a less opinionated default.
