### ISSUE TITLE
Immutable state

### ISSUE THREAD

**Issue by sebas5384** [matthewmueller/socrates#6]
What are the benefits of using the "update" method instead of the "replace" ?

Using something like [Mori](https://github.com/swannodette/mori) or [Immutable.js](https://github.com/facebook/immutable-js) shouldn't be faster enough?

I'm curious to know more about the deal with frozen state, of the state, to me doesn't seems so immutable, and looks like state isn't a value and more like a space to hold some value. [The Value of Values with Rich Hickey Talk](https://www.youtube.com/watch?v=-6BsiVyC1kM)

**Comment by matthewmueller** [comment]
this is 2 questions, so i'll answer them separately:

**what's the benefit of using update vs. just replacing**

replace vs. update is primarily a developer experience decision. mostly just to reduce boilerplate and prevent accidental state modification errors. but you can always return the full state object and just update the whole thing. 

**why not use mori or immutable.js**

mostly just to keep the build small.

we basically accomplish the same thing as mori and immutable by using an internal updater (that handles the mutations for you) and frozen state (which prevents you from making direct modifications to the state object).

with that said, i'm not an expert in immutable data structures, but this is just what i've picked up through reading and watching talks like the one you linked :-)
